[package]
name = "liz"
description = "LuaWizard - Features a bunch of functionalities for lua scripts inside the liz global variable."
repository = "https://github.com/emuvi/liz/"
authors = ["Éverton M. Vieira"]
license = "LGPL-3.0-only"
version = "0.1.19"
edition = "2018"

[dependencies]
rlua = "0.19"
simple-error = "0.2"
num_cpus = "1"
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = "1"
